# base image  
FROM python:3.8   
 
WORKDIR /usr/src/app
 
COPY requirements.txt ./
# install dependencies  
RUN pip install --upgrade pip  
RUN pip install -r requirements.txt

COPY . .

# start server  
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"] 
  